name: PR assignment

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: github.repository == 'thedjnK/AuTerm'
    steps:
      - name: 'Auto-assign PR'
        uses: thedjnK/auto-assign-issue@v2.1.2
        with:
          assignees: thedjnK
